language: ruby
rvm:
- 2.6.0
- 2.5.0
- 2.4.0
- 2.3.0
before_install:
  - gem install bundler -v '~> 2'
gemfile:
  - gemfiles/5.0.gemfile
  - gemfiles/5.1.gemfile
  - gemfiles/5.2.gemfile
  - gemfiles/6.0.gemfile
matrix:
  exclude:
    - rvm: 2.3.0
      gemfile: gemfiles/6.0.gemfile
    - rvm: 2.4.0
      gemfile: gemfiles/6.0.gemfile
cache:
  - bundler
